import React,{useState,useEffect}from'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Routes,Route,Link,NavLink}from'react-router-dom';
import{ShieldCheck,Menu,X,Phone,Mail,MapPin,MessageCircle,ArrowRight,ChevronLeft,ChevronRight,Shield,Users,Ship,Binoculars,Building2,Dog,Car,Siren,SearchCheck,Plane,BriefcaseBusiness,Camera,BellRing,ScanLine,Radio,DoorOpen,KeyRound,LocateFixed,PackageSearch,Flame,LockKeyhole,HardHat,Eye}from'lucide-react';
import'./style.css';
const services=[['Guard Services',Shield],['Escort Services',Car],['Event Security & Party Stewards',Users],['Maritime Security Services',Ship],['Risk & Crisis Management',Siren],['Investigation & Surveillance',Binoculars],['Security Consultancy',BriefcaseBusiness],['Corporate Guard Training',Building2],['Journey Management',Car],['Employee Background Vetting',SearchCheck],['Airport Reception & Protocol',Plane],['Dog Training & Handling',Dog],['VIP & Personal Protection',ShieldCheck]];
const desc={
'Guard Services':'Trained guards for homes, offices, institutions and industrial facilities.',
'Escort Services':'Professional escort for executives, assets and authorised movements.',
'Event Security & Party Stewards':'Access control, crowd management, patrol and event stewarding.',
'Maritime Security Services':'Security support for vessels, terminals and coastal operations.',
'Risk & Crisis Management':'Risk assessment, emergency planning and crisis coordination.',
'Investigation & Surveillance':'Discreet investigation, surveillance and lawful subject trailing.',
'Security Consultancy':'Security audits, planning, policies and professional advice.',
'Corporate Guard Training':'Training for guards, supervisors and corporate security teams.',
'Journey Management':'Route planning, movement coordination and travel risk support.',
'Employee Background Vetting':'Personal screening, identity verification and background checks.',
'Airport Reception & Protocol':'Airport reception, guest handling and protocol assistance.',
'Dog Training & Handling':'Professional security dog training and handling.',
'VIP & Personal Protection':'VIP escorts and personal protection specialist services.'};

const securityProducts=[
['CCTV Systems',Camera,'Sales, installation and maintenance of closed-circuit television systems for homes, offices, facilities and operational sites.'],
['Intruder Alarm Systems',BellRing,'Building and vehicle alarm systems designed to support early warning, deterrence and rapid response.'],
['Bomb-Screening Equipment',ScanLine,'Specialist screening and detection devices for approved security operations and controlled environments.'],
['GSM Signal-Control Solutions',Radio,'Specialist signal-control equipment supplied only where legally authorised and appropriately licensed.'],
['Electronic Door Supervision',DoorOpen,'Electronic door monitoring, access supervision and controlled-entry solutions for buildings and facilities.'],
['Electronic Key Holding & Alarm Response',KeyRound,'Secure electronic key-holding, alarm notification and response-support systems.'],
['Metal & Weapon Detection',ScanLine,'Handheld metal scanners and walk-through metal or weapon-detection systems for controlled access points.'],
['GPS+ Vessel & Vehicle Tracking',LocateFixed,'Tracking solutions for vessels, vehicles, mobile assets and journey-management operations.'],
['Baggage Screening Systems',PackageSearch,'Baggage and parcel screening equipment for airports, facilities, events and secure locations.'],
['Fire Safety Equipment',Flame,'Fire-fighting gear, fire extinguishers and related workplace emergency-response equipment.'],
['Armoured Doors & Secure Storage',LockKeyhole,'Armoured doors and safe-deposit boxes in multiple sizes for commercial and private use.'],
['Armoured & Ballistic Protection',ShieldCheck,'Bullet-resistant bullion vans for lease or sale, ballistic vests and other approved protective equipment.'],
['Restraint & Defensive Equipment',Shield,'Handcuffs, thumb cuffs, leg cuffs and other regulated security equipment supplied subject to applicable laws and approvals.'],
['Workplace Safety Gear',HardHat,'Safety boots, heavy-duty gloves, safety goggles, raincoats, overalls, reflective jackets and related protective clothing.'],
['Specialist Tactical Accessories',Eye,'Tactical pens, approved defensive devices and related specialist equipment supplied only where lawful and authorised.']
];
function ProductGrid(){return <section className="products-section"><div className="products-intro"><i>Security Technology & Equipment</i><h2>International Security Systems, Gadgets and Protective Equipment</h2><p>Through our relationship with international security bodies, including ISDS UK, we supply, install and maintain professional security technology and protective equipment for approved clients and operations.</p></div><div className="product-grid">{securityProducts.map(([title,Icon,text])=><article key={title}><span><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="compliance-note">All restricted, signal-control, defensive and specialist equipment is supplied only where permitted by applicable law, licensing requirements and authorised end-use procedures.</p></section>}

const slides=[
['Offshore & Maritime Protection','Protecting Maritime Operations and Valuable Assets','Professional offshore and maritime security support for vessels, logistics and critical operations.','one','/images/maritime-boat.jpg'],
['Trusted Security Professionals','Professional Guard & Corporate Security Services','Highly trained guards providing dependable protection for people, facilities and events.','two','/images/security-guards.webp'],
['Specialist Maritime Protection','Maritime Security Guard Services','Professional port protection, surveillance and security support for vessels and maritime facilities.','three','/images/maritime-guards.jpg']
];
function Header(){const[o,setO]=useState(false);return <><div className="top">Professionalism Per Excellence <a href="tel:+2348033219102">Emergency: 08033219102</a></div><header><Link className="brand" to="/"><b><ShieldCheck/></b><span>ABORD SECURITY<small>Services Limited</small></span></Link><button className="menu" onClick={()=>setO(!o)}>{o?<X/>:<Menu/>}</button><nav className={o?'open':''}>{[['Home','/'],['About','/about'],['Services','/services'],['Blog','/blog'],['Contact','/contact']].map(([n,p])=><NavLink onClick={()=>setO(false)} key={p} to={p}>{n}</NavLink>)}<a className="wa" href="https://wa.me/2348091034330">WhatsApp</a></nav></header></>}
function Footer(){return <footer><div><h3>ABORD SECURITY</h3><p>Reliable protection delivered with discipline, discretion and excellence.</p></div><div><h3>Headquarters</h3><p>#33 Bekweri Wosu (Igboukwu) Street, D/Line, Port Harcourt, Rivers State.</p><p>P.O. Box 8555, Federal Secretariat, Port Harcourt.</p></div><div><h3>Contact</h3><p>08033219102 · 08062952951<br/>08173386869 · 08027334585</p><p>abordsecurity@gmail.com</p><Link to="/privacy-policy">Privacy Policy</Link></div></footer>}
function PageHero({tag,title,text,image,alt}){return <section className="pagehero"><div className="pagehero-copy"><i>{tag}</i><h1>{title}</h1><p>{text}</p></div><div className="pagehero-media"><div className="rgb-frame page-rgb-frame"><img src={image} alt={alt||title}/></div></div></section>}
function Cards({items=services}){return <div className="cards">{items.map(([t,I])=><article key={t}><span><I/></span><h3>{t}</h3><p>{desc[t]}</p></article>)}</div>}
function Home(){const[a,setA]=useState(0);useEffect(()=>{let x=setInterval(()=>setA(v=>(v+1)%3),6000);return()=>clearInterval(x)},[]);return <><section className="slider">{slides.map((s,i)=><div key={s[1]} className={`slide ${s[3]} ${a===i?'active':''}`}><div className="hero-wrap"><div className="hero"><i>{s[0]}</i><h1>{s[1]}</h1><p>{s[2]}</p><Link className="btn" to="/services">Explore Services <ArrowRight/></Link><Link className="btn outline" to="/contact">Request Security Support</Link></div><div className="hero-media"><div className="rgb-frame"><img src={s[4]} alt={s[1]}/></div></div></div></div>)}<button className="arr left" onClick={()=>setA((a+2)%3)}><ChevronLeft/></button><button className="arr right" onClick={()=>setA((a+1)%3)}><ChevronRight/></button><div className="dots">{slides.map((_,i)=><button key={i} aria-label={`Show slide ${i+1}`} className={a===i?'active':''} onClick={()=>setA(i)}/>)}</div></section><ProductGrid/><section className="section split"><div><i className="green">About Abord Security</i><h2>Professionalism Per Excellence</h2><p className="lead">Abord Security Services Limited provides dependable security solutions for individuals, organisations, events and specialised operations.</p><p>Our approach combines trained personnel, careful planning, supervision and rapid response.</p><Link className="more" to="/about">Learn more <ArrowRight/></Link></div><div className="rgb"><Shield/><h3>Your Security Is Our Responsibility</h3><p>Prepared. Alert. Professional.</p></div></section><section className="dark"><div className="heading"><i>Core Services</i><h2>Complete Security Solutions</h2></div><Cards items={services.slice(0,6)}/><Link className="btn center" to="/services">View All Services</Link></section><section className="cta"><h2>Speak With Our Security Team</h2><p>Discuss your security requirements with us today.</p><a className="btn" href="tel:+2348033219102">Call Now</a> <a className="btn outline" href="https://wa.me/2348091034330">WhatsApp</a></section></>}
function About(){return <><PageHero tag="About Our Company" title="Security Built on Professionalism, Trust and Excellence" text="Carefully planned services protecting people, property and operations." image="/images/security-guards.webp" alt="Abord Security professional guards"/><section className="section split"><div><h2>Abord Security Services Limited</h2><p className="lead">A professional security company headquartered in Port Harcourt, Rivers State.</p><p>We serve individuals, companies, institutions, event organisers and maritime operators under clear procedures and strong supervision.</p></div><div className="values"><article><h3>Mission</h3><p>To protect lives, property and operations through trained people and sound planning.</p></article><article><h3>Vision</h3><p>To be a trusted security partner known for integrity and excellence.</p></article><article><h3>Motto</h3><p>Professionalism Per Excellence.</p></article></div></section></>}
function Services(){return <><PageHero tag="Our Services" title="Professional Security Services for Every Level of Risk" text="Solutions tailored to the client, location and operational requirement." image="/images/maritime-guards.jpg" alt="Maritime security guards at a port"/><ProductGrid/><section className="dark"><div className="heading"><i>Protective Services</i><h2>Professional Manpower and Operational Support</h2></div><Cards/></section></>}
function Blog(){return <><PageHero tag="Security Blog" title="Security Insights and Professional Guidance" text="Practical information for individuals and organisations." image="/images/maritime-boat.jpg" alt="Offshore security boat and cargo ship"/><section className="section blog">{[['Five Ways to Improve Security at Your Business','Improve access control, lighting, awareness and reporting.'],['Why Event Security Planning Matters','Good planning supports crowd control, emergency response and safer events.'],['The Value of Employee Background Screening','Structured vetting supports trusted hiring and protects assets.']].map(([t,d])=><article key={t}><ShieldCheck/><h2>{t}</h2><p>{d}</p><button className="more">Read article</button></article>)}</section></>}
function Contact(){return <><PageHero tag="Contact Us" title="Speak With Our Security Team" text="Contact us about guard services, executive protection, event security or investigations." image="/images/security-guards.webp" alt="Abord Security personnel"/><section className="section contact"><div className="details"><article><MapPin/><div><h3>Headquarters</h3><p>#33 Bekweri Wosu (Igboukwu) Street, D/Line, Port Harcourt, Rivers State.</p><p>P.O. Box 8555, Federal Secretariat.</p></div></article><article><Phone/><div><h3>Phone Lines</h3><p>08033219102<br/>08062952951<br/>08173386869<br/>08027334585</p></div></article><article><MessageCircle/><div><h3>WhatsApp</h3><p>08091034330</p></div></article><article><Mail/><div><h3>Email</h3><p>abordsecurity@gmail.com</p></div></article></div><form onSubmit={e=>e.preventDefault()}><h2>Request a Consultation</h2><input placeholder="Full name" required/><input placeholder="Phone number" required/><input type="email" placeholder="Email address"/><select><option>Select a service</option>{services.map(s=><option key={s[0]}>{s[0]}</option>)}</select><textarea rows="6" placeholder="Describe your security requirement"></textarea><button className="btn">Submit Request</button><small>Connect this form to EmailJS, Formspree or your VPS backend before launch.</small></form></section></>}
function Privacy(){return <><PageHero tag="Privacy Policy" title="How We Handle Personal Information" text="A general notice for information submitted through this website." image="/images/maritime-guards.jpg" alt="Professional maritime security team"/><section className="section policy"><h2>Information We Collect</h2><p>We may collect your name, phone number, email, organisation and enquiry details.</p><h2>How We Use Information</h2><p>Information may be used to respond to enquiries, prepare proposals and meet lawful obligations.</p><h2>Protection and Sharing</h2><p>We apply reasonable safeguards and do not sell personal information.</p><h2>Contact</h2><p>Email abordsecurity@gmail.com or call 08033219102.</p><blockquote>Have this policy reviewed by a qualified legal professional before final deployment.</blockquote></section></>}
function App(){return <BrowserRouter><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/blog" element={<Blog/>}/><Route path="/contact" element={<Contact/>}/><Route path="/privacy-policy" element={<Privacy/>}/></Routes></main><Footer/></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
